on:
    push:
        branches: -main
name: 🚀 Deploy website on push
jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: sidehustle.ng
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_SECRET }}
                  server-dir: /test.sidehustle.ng/test
                  port: 21
